
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 23 14:49:17 CEST 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVEQ = 44;
  public static final int CONST = 30;
  public static final int MODEQ = 45;
  public static final int NUMCONST = 46;
  public static final int NOTEQUAL = 36;
  public static final int GREATER = 39;
  public static final int LPAREN = 21;
  public static final int SEMI = 5;
  public static final int CONTINUE = 17;
  public static final int LESS = 35;
  public static final int FOR = 25;
  public static final int MINUS = 12;
  public static final int RPAREN = 22;
  public static final int AND = 11;
  public static final int LESSEQUAL = 38;
  public static final int OR = 10;
  public static final int COMMA = 27;
  public static final int INC = 8;
  public static final int DIV = 19;
  public static final int PLUSEQ = 41;
  public static final int MINUSEQ = 42;
  public static final int PLUS = 16;
  public static final int ASSIGN = 23;
  public static final int IF = 28;
  public static final int LSQBRACE = 6;
  public static final int DOT = 13;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 34;
  public static final int TRUE = 32;
  public static final int NEW = 31;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 18;
  public static final int MOD = 20;
  public static final int IDENT = 49;
  public static final int BREAK = 26;
  public static final int VOID = 24;
  public static final int MULEQ = 43;
  public static final int GREATEREQUAL = 37;
  public static final int LBRACE = 3;
  public static final int ELSE = 29;
  public static final int READ = 40;
  public static final int CHARCONST = 47;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 48;
  public static final int RSQBRACE = 7;
  public static final int DEC = 9;
  public static final int FALSE = 33;
  public static final int PRINT = 14;
}

